- name: Print Operation
  ansible.builtin.debug:
    msg: Operation {{ operation }}

- name: Test Environment variable "operation"
  fail: msg="Operation is not defined"
  when: (operation is undefined or operation|length == 0)

- name: Include Bootstrap tasks
  include_tasks: bootstrap.yaml
  when: (operation is search("bootstrap"))

- name: Include K3s Server tasks
  include_tasks: server.yaml
  when: (operation is search("server"))

- name: Include K3s Network tasks
  include_tasks: network.yaml
  when: (operation is search("network"))

- name: Include K3s Cert Manager tasks
  include_tasks: certmgr.yaml
  when: (operation is search("certmgr"))

- name: Include K3s Config tasks
  include_tasks: config.yaml
  when: (operation is search("config"))

- name: Include K3s Istio tasks
  include_tasks: istio.yaml
  when: (operation is search("istio"))

- name: Include K3s Worker tasks
  include_tasks: agent.yaml
  when: (operation is search("agent"))


