- name: Install Python packages for the module "kubernetes.core.k8s"
  ansible.builtin.pip:
    name: " {{ item }}"
    executable: "{{ virtualenv_pip3 }}"
  loop:
    - kubernetes
    - PyYAML
    - jsonpatch

- name: Check if Service Exists
  ansible.builtin.stat: "path=/etc/systemd/system/k3s.service"
  register: k3s_service_status

- name: Deploy K3s server
  block:
  - name: Run K3s deployment script in server mode
    ansible.builtin.shell:
      cmd: curl -sfL https://get.k3s.io | sh -
    environment:
      K3S_KUBECONFIG_MODE: "644"
      INSTALL_K3S_EXEC: "--flannel-backend=none --cluster-cidr={{ cluster_cidr }} --disable-network-policy --disable=traefik"
  when: not k3s_service_status.stat.exists



