- name: K3s Bootstrap
  hosts: localhost
  become: true
  
  roles:
    - k3s

  vars: {
    certmgr_path: "https://github.com/cert-manager/cert-manager/releases/download/v1.10.1/cert-manager.yaml",

# node_token: "{{ lookup('file','/tmp/node-token') }}"
# control_node_url: "{{ lookup('file','/tmp/control-node-url') }}"

    network_interface: "enp0s1",

    virtualenv_pip3: /home/ubuntu/python-venv/ansible/bin/pip3,
    ansible_python_interpreter: /home/ubuntu/python-venv/ansible/bin/python3
  }